config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  # devise_for :parents
  # devise_for :teachers
  # resources :teachers, expect: :show
  # resources :parents

  # resources :students
  # resources :courses

  # root to: 'pages#home'

  # get 'contact', to: 'pages#contact'
  # get 'careers', to: 'pages#careers'


  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
  end

  resources :users
  resources :parents
  resources :teachers
  # resources :exam_categories
  resources :lessons

  resources :students
  # resources :exams
  resources :courses
  resources :lessons

  # root 'dashboard#index'
  root 'pages#home'
end

app/models/student.rb
class Student < ApplicationRecord

devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  belongs_to :parent
  belongs_to :course
  has_many :lessons
  has_one :teacher, through: :course


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    # raise
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id].to_i)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :age, :level, :course, :email, :password)
    end
end

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>
  <%= f.error_notification %>
  <% DateTime.now.strftime("%d/%m/%Y - %H:%M %p") %>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :parent_id, collection: Parent.all %>
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.input :age, as: :date, start_year: Date.today.year - 15,
                            end_year: Date.today.year - 12, discard_day: false,
                              order: [:day, :month, :year] %>
      <%= f.input :course_id, collection: Course.all %>
    </div>
  </div>
  <%= f.button :submit, class: 'btn btn-primary btn-fill' %>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<% if current_teacher.admin? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-users"></i>
        Listing Students
      </h4>
      <hr/>
      <%= link_to new_student_path, class: 'btn btn-primary btn-fill' do %>
        <i class="fa fa-plus-square"></i>
        New Student
      <% end %>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Level</th>
            <th>Email</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
            <tr>
              <td>
                <%= student.first_name %> <%= student.last_name %>
              </td>
              <td>
                <%= student.age %>
              </td>
              <td>
                <%= student.level %>
              </td>
              <td>
                <%= student.email %>
              </td>
              <td>
                <%= link_to student, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
                <%= link_to edit_student_path(student), class: 'btn btn-primary btn-sm' do %>
                  <i class="fa fa-edit"></i>
                  Edit
                <% end %>
                <%= link_to student, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
                  <i class="fa fa-trash"></i>
                  Delete
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% current_teacher.admin? == false %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-users"></i>
        Your Students
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
       <thead>
          <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Level</th>
            <th>Email</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% current_teacher.students.each do |student| %>
            <tr>
              <td>
                <%= student.first_name %> <%= student.last_name %>
              </td>
              <td>
                <%= student.age %>
              </td>
              <td>
                <%= student.level %>
              </td>
              <td>
                <%= student.email %>
              </td>
              <td>
                <%= link_to student, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% parent_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-users"></i>
        Seus filhos
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Level</th>
            <th>Curso</th>
            <th>Email</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% current_parent.students.each do |student| %>
            <tr>
              <td>
                <%= student.first_name %> <%= student.last_name %>
              </td>
              <td>
                <%= student.age %>
              </td>
              <td>
                <%= student.level %>
              </td>
              <td>
                <%= student.course.name %>
              </td>
              <td>
                <%= student.email %>
              </td>
              <td>
                <%= link_to student, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% else %>
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Student</h4>
      <hr/>
    </div>
    <div class="content">
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <table class="table">
            <tr>
              <th>Image</th>
              <td>
                <%#image_tag @student.photo, size: '150x150' %>
              </td>
            </tr>
            <tr>
              <th>Name</th>
              <td>
                <%= @student.first_name %> <%=@student.last_name %>
              </td>
            </tr>
            <tr>
              <th>Parent Name</th>
              <td>
                <%= link_to "#{@student.parent.first_name}", @student.parent %>
              </td>
            </tr>
            <tr>
              <th>Date of Birth</th>
              <td>
                <%= @student.age %>
              </td>
            </tr>
            <tr>
              <th>level</th>
              <td>
                <%= @student.level %>
              </td>
            </tr>
            <tr>
              <th>Email</th>
              <td>
                <%= @student.email %>
              </td>
            </tr>
            <tr>
              <th>Course</th>
              <% if @student.course != nil %>
              <td>
                <%= link_to "#{@student.course.name}", @student.course %>
              </td>
              <% else %>
              <td>
                You're not enrolled in any course yet
              </td>
              <% end %>
            </tr>
             <tr>
              <% if @student.course != nil %>
              <th>Teacher</th>
              <td>
                <%= @student.teacher.first_name %>
              </td>
              <% else %>
              <td>
                <p></p>
              </td>
              <% end %>
            </tr>
          </table>
        </div>
    </div>
    <div class="footer">
      <%= link_to students_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
      <%= link_to edit_student_path(@student), class: 'btn btn-primary btn-fill' do %>
        <i class="fa fa-edit"></i>
        Edit
      <% end %>
    </div>
    <br/>
  </div>
</div>