config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  # devise_for :parents
  # devise_for :teachers
  # resources :teachers, expect: :show
  # resources :parents

  # resources :students
  # resources :courses

  # root to: 'pages#home'

  # get 'contact', to: 'pages#contact'
  # get 'careers', to: 'pages#careers'


  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
  end

  resources :users
  resources :parents
  resources :teachers
  # resources :exam_categories
  resources :lessons

  resources :students
  # resources :exams
  resources :courses
  resources :lessons

  # root 'dashboard#index'
  root 'pages#home'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-speakit_live">
  <!-- Logo -->
  <a href="/" class="navbar-speakit_live-brand">
    <%= image_tag "https://previews.123rf.com/images/dvarg/dvarg1603/dvarg160300020/52984920-illustration-of-a-friendly-cute-bee-flying-and-smiling.jpg" %>
  </a>

  <!-- Right Navigation -->
    <div class="navbar-speakit_live-right hidden-xs hidden-sm">
      <% if teacher_signed_in? %>

        <!-- When Teacher is Signed In -->
        <%= link_to "Courses", courses_path, class: "navbar-speakit_live-item" %>
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag 'teacher_icon.png', class: "navbar-icon dropdown-toggle", id: "navbar-wagon-menu", "data-toggle": "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><%= link_to "Log Out", destroy_teacher_session_path, method: :delete, class: "navbar-speakit_live-item navbar-speakit_live-link" %></li>
            </ul>
          </div>
        </div>

      <% elsif student_signed_in? %>

        <!-- When Student is Signed In -->
        <%= link_to "Courses", courses_path, class: "navbar-speakit_live-item" %>
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag 'student_icon.png', class: "navbar-icon dropdown-toggle", id: "navbar-wagon-menu", "data-toggle": "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><%= link_to "Log Out", destroy_student_session_path, method: :delete, class: "navbar-speakit_live-item navbar-speakit_live-link" %></li>
            </ul>
          </div>
        </div>

        <% elsif parent_signed_in? %>

        <!-- When Student is Signed In -->
        <%= link_to "Courses", courses_path, class: "navbar-speakit_live-item" %>
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag 'student_icon.png', class: "navbar-icon dropdown-toggle", id: "navbar-wagon-menu", "data-toggle": "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><%= link_to "Log Out", destroy_parent_session_path, method: :delete, class: "navbar-speakit_live-item navbar-speakit_live-link" %></li>
            </ul>
          </div>
        </div>

      <% else %>


          <!-- Parent Sign In -->
        <%= link_to parent_session_path, class: "navbar-icon-link" do %>
          <%= image_tag 'teacher_icon.png', class: "navbar-icon"%>
          <small>Parent</small>
        <% end %>
        <!-- Student Sign In -->
        <%= link_to student_session_path, class: "navbar-icon-link" do  %>
           <%= image_tag 'student_icon.png', class: "navbar-icon"%>
          <small>Student</small>
        <% end %>

        <!-- Teacher Sign In -->
        <%= link_to teacher_session_path, class: "navbar-icon-link" do %>
          <%= image_tag 'teacher_icon.png', class: "navbar-icon"%>
          <small>Teacher</small>
        <% end %>



      <% end %>









      <!-- Profile picture with dropdown list -->

    </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-speakit_live-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-speakit_live-dropdown-menu">

        <!-- Teacher Sign In or Sign Up -->
        <% if !student_signed_in? && !teacher_signed_in? %>
          <li><%= link_to "Teacher Sign In", teacher_session_path %></li>
        <% end %>

        <!-- Student Sign In or Sign Up -->
        <% if !student_signed_in? && !teacher_signed_in? %>
          <li><%= link_to "Student Sign In", student_session_path %></li>
        <% end %>

        <!-- Teacher is Signed In -->
        <% if teacher_signed_in? %>
          <li><%= link_to "Courses", courses_path %></li>
          <li><%= link_to "Teacher Sign Out", destroy_teacher_session_path, method: :delete %></li>
        <% end %>

        <% if student_signed_in? %>
          <li><%= link_to "Courses", courses_path %></li>
          <li><%= link_to "Student Sign Out", destroy_student_session_path, method: :delete %></li>
        <% end %>

        <% if parent_signed_in? %>
          <li><%= link_to "Courses", courses_path %></li>
          <li><%= link_to "Parent Sign Out", destroy_parent_session_path, method: :delete %></li>
        <% end %>

      </ul>
    </div>
  </div>
</div>