config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  # devise_for :parents
  # devise_for :teachers
  # resources :teachers, expect: :show
  # resources :parents

  # resources :students
  # resources :courses

  # root to: 'pages#home'

  # get 'contact', to: 'pages#contact'
  # get 'careers', to: 'pages#careers'


  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
  end

  resources :users
  resources :parents
  resources :teachers
  # resources :exam_categories
  resources :lessons

  resources :students
  # resources :exams
  resources :courses
  resources :lessons

  # root 'dashboard#index'
  root 'pages#home'
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true


  has_many :courses
  has_many :students, through: :courses

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  skip_before_action :authenticate_teacher!

  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.create(teacher_params)
    if @teacher.save
      redirect_to teachers_path
    else
      render :new
    end
  end

  def index
    if params[:first_name].blank?
      @teachers = Teacher.all
    else
      @teachers = Teacher.select do |teacher|
      teacher.first_name == params[:first_name]
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    @teacher.update(teacher_params)
    redirect_to teacher_path
  end

  def destroy
    @teacher.destroy
    redirect_to teachers_path
  end

  private

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :language, :email)
  end

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :Language %>
    <%= f.text_field :language, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/teachers/edit.html.erb
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Edit Teacher</h4>
      <hr/>
    </div>
    <div class="content">
      <%= render 'form' %>
    </div>
    <hr/>
    <div class="footer">
      <%= link_to teachers_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
      <%= link_to @teacher, class: 'btn btn-info btn-fill' do %>
        <i class="fa fa-eye"></i>
        Show
      <% end %>
    </div>
    <br/>
  </div>
</div>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_teacher.admin? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-users"></i>
        Listing Teachers
      </h4>
      <hr/>
      <%= link_to new_teacher_path, class: 'btn btn-primary btn-fill' do %>
        <i class="fa fa-plus-square"></i>
        New Teacher
      <% end %>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Language</th>
            <th>Email</th>
            <th>Admin?</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @teachers.each do |teacher| %>
            <tr>
              <td>
                <%= teacher.first_name %>
              </td>
              <td>
                <%= teacher.last_name%>
              </td>
              <td>
                <%= teacher.language %>
              </td>
               <td>
                <%= teacher.email %>
              </td>
              <td>
                <%= teacher.admin? %>
              </td>
              <td>
                <%= link_to teacher, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
                <%= link_to edit_teacher_path(teacher), class: 'btn btn-primary btn-sm' do %>
                  <i class="fa fa-edit"></i>
                  Edit
                <% end %>
                <%= link_to teacher, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
                  <i class="fa fa-trash"></i>
                  Delete
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% student_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-users"></i>
        Professor
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Sobrenome</th>
            <th>Lingua</th>
            <th>email</th>
          </tr>
        </thead>
        <tbody>
          <% if current_student.course != nil %>
            <tr>
              <td>
                <%= current_student.teacher.first_name %>
              </td>
              <td>
                <%= current_student.teacher.last_name %>
              </td>
              <td>
                <%= current_student.teacher.language %>
              </td>
              <td>
                <%= link_to current_student.teacher, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% parent_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-users"></i>
        Professor(es)
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Aluno</th>
            <th>Nome do professor</th>
            <th>Lingua</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          <% current_parent.students.each do |student| %>
            <tr>
              <td>
                <%= student.first_name %>
              </td>
              <td>
                <%= student.teacher.first_name %>
              </td>
              <td>
                <%= student.teacher.language %>
              </td>
              <td>
                <%= student.teacher.email %>
              </td>
              <td>
                <%= link_to student.teacher, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% else %>
<p>Private page</p>
<% end %>

app/views/teachers/new.html.erb
<<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">New Teacher</h4>
      <hr/>
    </div>
    <div class="content">
      <%= render 'form' %>
    </div>
    <hr/>
    <div class="footer">
      <%= link_to teachers_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
    </div>
    <br/>
  </div>
</div>

app/views/teachers/show.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Teacher</h4>
      <hr/>
    </div>
    <div class="content">
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <table class="table">
            <tr>
               <%= image_tag @teacher.photo, size: '150x150' %>
            </tr>
            <tr>
              <th>Name</th>
              <td>
                <%= @teacher.first_name %> <%=@teacher.last_name %>
              </td>
            </tr>
            <tr>
              <th>Language</th>
              <td>
                <%= @teacher.language %>
              </td>
            </tr>

            <th>Email</th>
              <td>
                <%= @teacher.email %>
              </td>
            </tr>

          </table>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= week_calendar number_of_weeks: 2 do |date| %>
  <%= date %>
<% end %>
          <div id="show-teacher-map"></div>
        </div>
      </div>
    </div>
    <div class="footer">
      <%= link_to teachers_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
      <%= link_to edit_teacher_path(@teacher), class: 'btn btn-primary btn-fill' do %>
        <i class="fa fa-edit"></i>
        Edit
      <% end %>
    </div>
    <br/>
  </div>
</div>