config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  # devise_for :parents
  # devise_for :teachers
  # resources :teachers, expect: :show
  # resources :parents

  # resources :students
  # resources :courses

  # root to: 'pages#home'

  # get 'contact', to: 'pages#contact'
  # get 'careers', to: 'pages#careers'


  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
  end

  resources :users
  resources :parents
  resources :teachers
  # resources :exam_categories
  resources :lessons

  resources :students
  # resources :exams
  resources :courses
  resources :lessons

  # root 'dashboard#index'
  root 'pages#home'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    if current_teacher.admin?
      @courses = Course.all
      @course = Course.new
    else
      # raise
      @teacher = current_teacher
    end
  end

  def show
    @course = Course.find(params[:id])
    @course.students
    # raise
    # @students = Student.find(params[:student_id])
  end

  def new
    if current_teacher.admin?
    @course = Course.new
  end

  def create
    @course = Course.create(course_params)
    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end

    if @course.save
      redirect_to course_path(@course)
    else
      render :new
    end
  end

  def edit
     @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    @course.update(course_params)
    redirect_to course_path
  end


  private

  def course_params
    params.require(:course).permit(:name, :level, :description, :teacher_id, :student_id)
  end
end

# ONLY ADMIN CAN CREATE COURSES
# ONCE THE COURSE IS CREATED, ADMIN MUST ASSIGN IT TO A TEACHER
# TEACHER CAN THEN ENTER COURSE

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <%= f.date_field :start_date %>
      <%= f.date_field :end_date %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :level, collection: Level.all %>
      <%= f.input :teacher, collection: Teacher.all %>
    </div>
  </div>
  <%= f.button :submit, class: 'btn btn-primary btn-fill' %>
<% end %>

app/views/courses/create.html.erb
<h1>Courses#create</h1>
<p>Find me in app/views/courses/create.html.erb</p>

app/views/courses/edit.html.erb
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Edit Course</h4>
      <hr/>
    </div>
    <div class="content">
      <%= render 'form' %>
    </div>
    <hr/>
    <div class="footer">
      <%= link_to courses_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
      <%= link_to @course, class: 'btn btn-info btn-fill' do %>
        <i class="fa fa-eye"></i>
        Show
      <% end %>
    </div>
    <br/>
  </div>
</div>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>


<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-ribbon"></i>
<% if current_teacher.admin? %>
        Listing Courses
      </h4>
      <hr/>
      <%= link_to new_course_path, class: 'btn btn-primary btn-fill' do %>
        <i class="fa fa-plus-square"></i>
        New Course
      <% end %>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Grade</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @courses.each do |course| %>
            <tr>
              <td>
                <%= course.name %>
              </td>
              <td>
                <%= course.description %>
              </td>
              <td>
                <%= course.level.name %>
              </td>
              <td>
                <%= link_to course, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
                <%= link_to edit_course_path(course), class: 'btn btn-primary btn-sm' do %>
                  <i class="fa fa-edit"></i>
                  Edit
                <% end %>
                <%= link_to course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
                  <i class="fa fa-trash"></i>
                  Delete
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% teacher_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-ribbon"></i>
        Listing your courses
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Grade</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% current_teacher.courses.each do |course| %>
            <tr>
              <td>
                <%= course.name %>
              </td>
              <td>
                <%= course.description %>
              </td>
              <td>
                <%= course.level.name %>
              </td>
              <td>
                <%= link_to course, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% student_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-ribbon"></i>
        Seu Curso
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Grade</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% if current_student.course != nil %>
            <tr>
              <td>
                <%= current_student.course.name %>
              </td>
              <td>
                <%= current_student.course.description %>
              </td>
              <td>
                <%= current_student.course.level.name %>
              </td>
              <td>
                <%= link_to current_student.course, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% parent_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-ribbon"></i>
        Seu curso(s)
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Nome do aluno</th>
            <th>Name</th>
            <th>Description</th>
            <th>Grade</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
           <% current_parent.students.each do |student| %>
            <tr>
              <td>
                <%= student.name %>
              </td>
              <td>
                <%= student.course.name %>
              </td>
              <td>
                <%= student.course.description %>
              </td>
              <td>
                <%= student.course.level.name %>
              </td>
              <td>
                <%= link_to student.course, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% else %>
<p>Private page</p>
<% end %>

app/views/courses/new.html.erb
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">New Course</h4>
      <hr/>
    </div>
    <div class="content">
      <%= render 'form' %>
    </div>
    <hr/>
    <div class="footer">
      <%= link_to courses_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
    </div>
    <br/>
  </div>
</div>

app/views/courses/show.html.erb
<% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Course</h4>
      <hr/>
    </div>
    <div class="content">
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <table class="table">
            <tr>
              <th>Name</th>
              <td>
                <%= @course.name %>
              </td>
            </tr>
            <tr>
              <th>Description</th>
              <td>
                <%= @course.description %>
              </td>
            </tr>
            <tr>
              <th>Start Date</th>
              <td>
                <%= @course.start_date %>
              </td>
              <tr>
              <th>End Date</th>
              <td>
                <%= @course.end_date %>
              </td>
            <tr>
              <th>Grade</th>
              <td>
                <%= @course.level.name %>
              </td>
            </tr>
            <tr>
              <th>Teacher</th>
              <td>
                <%= @course.teacher.first_name %>
              </td>
            </tr>
            <tr>
              <th>Students enrolled</th>
              <td>
                <% @course.students.each do |student| %>
              <ul>
                <li style="list-style: none">
                  <%= student.first_name %>
                </li>
              </ul>
                <% end %>
              <tr>
                <th>Lessons</th>
                <td>
                <% @course.lessons.each do |lesson| %>
                <ul>
                  <%= link_to lesson.name, lesson_path %>
                </ul>
                <% end %>
              </td>
              </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="footer">
      <%= link_to courses_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
      <%= link_to edit_course_path(@course), class: 'btn btn-primary btn-fill' do %>
        <i class="fa fa-edit"></i>
        Edit
      <% end %>
    </div>
    <br/>
  </div>
</div>